version: '3'
services:
    mysql:
        image: "mariadb:10.4"
        restart: always
        environment:
            MYSQL_PASSWORD: "${STEMWEB_DBPASS}"
            MYSQL_USER: "${STEMWEB_DBUSER}"
            MYSQL_RANDOM_ROOT_PASSWORD: "YES"
            MYSQL_DATABASE: "${STEMWEB_DBNAME}"

    redis:
        image: "redis:alpine"
        restart: always
        sysctls:
            # change this Linux Kernel Parameter (default is 128) within container because of this WARNING
            # "The TCP backlog setting of 511 cannot be enforced
            # because /proc/sys/net/core/somaxconn is set to the lower value of 128."
            net.core.somaxconn: 512     # maximal number of connections
        volumes:
            - ./redisinit/redis.conf:/usr/local/etc/redis/redis.conf       # version 6 from  https://redis.io/topics/config     ## adapted
        command:
            redis-server /usr/local/etc/redis/redis.conf

    stemweb:
        build: .
        restart: always
        depends_on:
            - mysql
            - redis
        env_file:
            - .env
        ports:
            - "127.0.0.1:8000:8000"
            - "127.0.0.1:51000:51000"

    client:
        build: client/
        restart: always
        depends_on:
            - stemweb
        volumes:
            - ./client:/src/app
        ports:
            - "127.0.0.1:8001:8001"